# Generated by Django 4.0.6 on 2022-07-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coriolis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Достоинства',
                'verbose_name_plural': 'Типы достоинства',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['name'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='type_advantage',
        ),
        migrations.AddField(
            model_name='advantage',
            name='advantage_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coriolis.advantagetype', verbose_name='Типы достоинств'),
        ),
    ]
